# Generated by Django 3.2.12 on 2022-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_remove_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
